---
title: "Dinámica de la precariedad laboral a partir de la EPH individual. 3T-2019/2023"
author: "Magdalena Tóffoli y Belén Morris"
output:
  flexdashboard::flex_dashboard:
   encoding: UTF-8
   social: menu
   runtime: shiny
---

```{r setup, include=FALSE}
library(rmarkdown)
library(dplyr)
library (ggplot2)
library(plotly)
library(flexdashboard)
library(shiny)
library(stringi)  # Para limpiar caracteres especiales
library(scales)
library(haven) #porque hay variables labelled que generan errores en la visualización
```

```{r}
#cargo algunos data frames de interés para este dashboard
load("datosparadashboard.RData")
```

```{r}
# Convertir caracteres a UTF-8 y limpiar acentos/tildes
eph_filtrada2 <- eph_filtrada2 %>%
  mutate(across(where(is.labelled), ~ as_factor(.))) %>%
  mutate(across(where(is.character), ~ stri_trans_general(., "Latin-ASCII")))  # Elimina tildes
```

# Tasas de precariedad por año

```{r}
# Crear gráfico con ggplot
grafico_Tasasprecariedad <- ggplot(TasasPrecariedad_1923_long, 
          aes(x = factor(ANO4), 
              y = Valor_tasa, 
              fill = Tasa_tipo,
          text = paste("Año: ", ANO4,
                 "<br>Tasa: ", round(Valor_tasa, 1), "%",
                 "<br>Tipo de tasa: ", Tasa_tipo)
          )
          
)+                  
            geom_bar(stat = "identity", position = "dodge") +  
  labs(       subtitle = "Total de 31 aglomerados. Terceros trimestres de 2019-2023",
       x = "Anio",
       y = "Tasa (%)",
       fill = "Tipo de tasa") + 
  scale_fill_brewer(palette = "Reds")+
  theme_minimal() + 
  scale_y_continuous(labels = scales::percent_format(scale = 1, big.mark = ".", decimal.mark = ","))
```

```{r}
# Convertir a gráfico interactivo y personalizar las etiquetas emergentes
grafinteractivo_precatotal <- ggplotly(grafico_Tasasprecariedad, 
                                      tooltip = "text")

# Mostrar el gráfico interactivo
grafinteractivo_precatotal
```

# Precariedad por variables demográficas

```{r}
#COn este código creamos el widget de shiny para seleccionar la variable de agrupación. 
# Interfaz de usuario-camnbio ui y server poque flexdashboard ya lo manera internamente
selectizeInput("Variable_demo", "Selecciona la variable de agrupacion:", 
               choices = c("Grupo etario" = "grupos_etarios", 
                           "Sexo" = "SEXO", 
                           "Lugar de nacimiento" = "lugar_nacimiento", 
                           "Nivel educativo" = "nivel_educativo_completo"), 
               selected = "grupos_etarios")
```

```{r}

#gráfico de niveles de precariedad
output$grafico_demo <- renderPlotly({
  req(input$Variable_demo)

    # Filtrar las filas donde la variable seleccionada no es NA
    datos_filtrados <- eph_filtrada2 %>% #datos filtrados nos sirve para luego construir el gráfico
      filter(!is.na(.data[[input$Variable_demo]])) %>%  # Filtra filas con NA en la variable seleccionada
      group_by(ANO4, .data[[input$Variable_demo]], Niveles_precariedad_total) %>%
      summarise(Niveles_precariedad_total_sum = sum(PONDERA, na.rm = TRUE), .groups = "drop") %>%
      mutate(porcentaje = Niveles_precariedad_total_sum / sum(Niveles_precariedad_total_sum) * 100)

    
    # Crear el gráfico
    p <- ggplot(datos_filtrados, aes(x = factor(ANO4), y = Niveles_precariedad_total_sum, fill = Niveles_precariedad_total,text = paste("Porcentaje: ", round(porcentaje, 2), "%")))     +
      geom_bar(stat = "identity", position = "dodge") +  
      guides(fill = guide_legend(title = "Niveles de precariedad")) +
      theme_minimal() +
      labs(title= "Evolución de los niveles de precariedad",
           x = "Anio",
           y = "Frecuencia absoluta",
           fill = "Niveles de Precariedad") + 
theme(axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom") +  # Mover la leyenda a la parte inferior
     #Rotar etiquetas del eje X si hay muchos años
      scale_y_continuous(labels = scales::comma) +  # Mantener los valores absolutos en el eje Y
      facet_wrap(~ .data[[input$Variable_demo]], scales = "free_y") +  # Usar facet_wrap para desagregar por la variable seleccionada
      scale_fill_brewer(palette ="Oranges")  # Colores para las categorías
  # Convertir el gráfico ggplot a plotly y añadir el tooltip
   p_plotly <- ggplotly(p, tooltip = "text")  
     # Personalizar colores en plotly para asegurarse de que la paleta "Oranges" se mantenga
    p_plotly <- p_plotly %>%
      layout(
        colorway = RColorBrewer::brewer.pal(9, "Oranges"),  # Usar la paleta de colores "Oranges" de RColorBrewer
         legend = list(orientation = "h", y = -0.3))  # Mover la leyenda a la izq del gráfico
        
    
    return(p_plotly)
  })

```
```{r}
#con esto renderizamos el gráfico generado por plotly
plotlyOutput("grafico_demo")
```

# Precariedad por variables laborales

```{r}
 # Interfaz de usuario
      selectizeInput(
        inputId = "Variable_lab", 
        label = "Selecciona la variable de agrupacion:", 
        choices = c("Categoria ocupacional" = "CAT_OCUP", 
                    "Tipo de empleador" = "ambito_establecimiento", 
                    "Sector de actividad" = "caes_eph_label"), 
        selected = "CAT_OCUP",
        width = "100%"  # Esto hace que el widget ocupe todo el espacio en el panel
      )
```

```{r}
    output$grafico_lab <- renderPlotly({
    req(input$Variable_lab)  

    # Filtrar las filas donde la variable seleccionada no es NA
    datos_filtrados2 <- eph_filtrada2 %>%
      filter(!is.na(.data[[input$Variable_lab]])) %>%  # Filtra filas con NA en la variable seleccionada
      mutate(
        CAT_OCUP = case_when(
          CAT_OCUP == 2 ~ "Trabajadores cuenta propia",
          CAT_OCUP == 3 ~ "Trabajadores asalariados",
          TRUE ~ as.character(CAT_OCUP)  # Mantener los demás valores sin cambios
        )
      ) %>%
      group_by(ANO4, .data[[input$Variable_lab]], Niveles_precariedad_total) %>%
      summarise(Niveles_precariedad_total_sum = sum(PONDERA, na.rm = TRUE), .groups = "drop") %>%
      group_by(ANO4, .data[[input$Variable_lab]]) %>%
      mutate(porcentaje = Niveles_precariedad_total_sum / sum(Niveles_precariedad_total_sum) * 100)

    
    # Crear el gráfico
    p <- ggplot(datos_filtrados2, aes(x = factor(ANO4), y = Niveles_precariedad_total_sum, fill = Niveles_precariedad_total,text = paste("Porcentaje: ", round(porcentaje, 2), "%")))     +
      geom_bar(stat = "identity", position = "dodge") +  
      guides(fill = guide_legend(title = "Niveles de precariedad")) +
      theme_minimal() +
      labs(title= "Evolución de los niveles de precariedad",
           x = "Anio",
           y = "Frecuencia absoluta",
           fill = "Niveles de Precariedad") + 
theme(axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom") +  # Mover la leyenda a la parte inferior
     #Rotar etiquetas del eje X si hay muchos años
      scale_y_continuous(labels = scales::comma) +  # Mantener los valores absolutos en el eje Y
      facet_wrap(~ .data[[input$Variable_lab]], scales = "free_y") +  # Usar facet_wrap para desagregar por la variable seleccionada
      scale_fill_brewer(palette ="Oranges")  # Colores para las categorías
  # Convertir el gráfico ggplot a plotly y añadir el tooltip
   p_plotly <- ggplotly(p, tooltip = "text")  
     # Personalizar colores en plotly para asegurarse de que la paleta "Oranges" se mantenga
    p_plotly <- p_plotly %>%
      layout(
        colorway = RColorBrewer::brewer.pal(9, "Oranges"),  # Usar la paleta de colores "Oranges" de RColorBrewer
         legend = list(orientation = "h", y = -0.3))  # Mover la leyenda a la izq del gráfico
        
    
    return(p_plotly)
  })

```
```{r}
plotlyOutput("grafico_lab")
```




